WIP: Add miniforge3 language
algorithmiaio/langpacks pull request #172
Opened 2020-11-17 15:59 UTC by danielfrg

Adding a new language pack for miniforge3.

- Miniforge is the Miniconda alternative from conda-forge - Using this instead  in order to be ok with the new license from Anaconda: https://www.anaconda.com/blog/anaconda-commercial-edition-faq
- This pack uses [`mamba`](https://github.com/mamba-org/mamba) as a package manager instead of conda - mamba is compatible with conda and a lot faster and its already being used in systems like conda-forge and binder

Other changes in the validator code:
- Fixes some jinja templates whitespace issues that were causing warnings and future errors on `docker build`
- Added the ability to see the progress of the `docker build` commands with the `--verbose/-v` flag
- Make the cleanup of the dockerfiles explicit, makes it a bit easier to debug

2020-11-23 18:15 UTC, zeryx requested changes
Works fine for python, but fails with other languages that require compilation:

for a java11 config.json:
```
{
    "display_name": "Java OpenJDK 11.0 (Environments)",
    "req_files": [
        "pom.xml"
    ],
    "artifacts": [
        {"source":"/opt/algorithm/target/*.jar", "destination":"/opt/algorithm/target/algorithm.jar"},
        {"source":"/opt/algorithm/target/lib", "destination":"/opt/algorithm/target/lib/"}
    ]
}


built with:
`./tools/environment_validator.py -s java11 -t language -n java11 -b ubuntu:20.04`

```
build process fails with the following message: 
```
Error: Could not find or load main class com.algorithmia.algorithm.Algorithm\n2020-11-23T18:13:03.104 INFO ALGOERR - Caused by: java.lang.ClassNotFoundException: com.algorithmia.algorithm.Algorithm\n'
```

^ the if/else switch in the jinja template does work; ideally if possible a more generalized solution would be worth implementing here.

2020-11-23 21:13 UTC, danielfrg commented
(On the last commit) I was able to get it working with:

```
{
    "display_name": "Java OpenJDK 11.0 (Environments)",
    "req_files": [
        "pom.xml",
        "src"
    ],
    "artifacts": [
        {"source":"/opt/algorithm/target/*.jar", "destination":"/opt/algorithm/target/algorithm.jar"},
        {"source":"/opt/algorithm/target/lib", "destination":"/opt/algorithm/target/lib/"}
    ]
}
```

On this case it wont do anything tho, as any changes in the algo source will trigger a rebuild of that layer.
I don't think i see a way to make this work for java since we are calling `mvn package` it will require the source.

We could change the build command to just `mvn install dependency:copy-dependencies` and move the `mvn package` to the runtime but it wouldn't really be runtime at that point.

2020-11-24 16:22 UTC, zeryx submitted a review, later dismissed
Fair enough @danielfrg , I think what we have now is sufficient to move forward with. Lets just add a `req_file` for python2, python3, and anaconda3 and we should be good to merge this.

2020-11-24 16:35 UTC, zeryx approved these changes

2020-11-24 16:35 UTC, merged